# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('appointment_id', models.CharField(max_length=100, unique=True)),
                ('scheduled_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(default=None, null=True)),
                ('time_waited', models.DurationField(null=True)),
                ('reference_time', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(default=b'', max_length=100)),
            ],
        ),
    ]
